title: Your Website Title
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://dean-98543.github.io"  # the base hostname & protocol for your site
kramdown:
  math_engine: mathjax
theme: minimal-mistakes-jekyll

